### ISSUE TITLE
Not working in the new terraform verison

### ISSUE THREAD

**Issue by arturohernandez10** [telia-oss/terraform-aws-sonarqube#14]
It would be very nice to have the required terraform version in the readme.

**Comment by itsdalmo** [comment]
Thanks for heads up, and sorry for the radio silence on our end. We will upgrade the required version to `>= 0.12` very soon, and then the required version will be documented in `versions.tf` (as part of `terraform 0.12upgrade`).

**Comment by itsdalmo** [comment]
Hi @arturohernandez10 - terraform 0.12 should be supported since merging #15. Will close this issue but feel free to open a new one if you run into problems/have any questions. Thanks!
