### ISSUE TITLE
Somehow the parameter is hardcoded?

### ISSUE THREAD

**Issue by arturohernandez10** [telia-oss/terraform-aws-sonarqube#4]
First I got this error

Error: Error applying plan:

2 error(s) occurred:

* module.sonarqube.module.sonarqube_service.aws_ssm_parameter.sonarqube-rds-url: 1 error(s) occurred:

* aws_ssm_parameter.sonarqube-rds-url: error creating SSM parameter: InvalidKeyId: Key 'arn:aws:kms:us-east-1:651476002431:key/080612b3-f414-4f76-af61-b7be55fa9b63' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: b9d21e02-9165-46ff-88f4-c6c6f8266ea4)
        status code: 400, request id: 3e486369-fd4d-4dc5-a5cd-5bd2ede96fff
* module.sonarqube.module.sonarqube_service.aws_ssm_parameter.sonarqube-base-url: 1 error(s) occurred:

* aws_ssm_parameter.sonarqube-base-url: error creating SSM parameter: InvalidKeyId: Key 'arn:aws:kms:us-east-1:651476002431:key/080612b3-f414-4f76-af61-b7be55fa9b63' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: 3ac71816-8a06-46a3-88c2-fc64bbcc159a)
        status code: 400, request id: 9f1cbfdc-b3e2-4d1c-a9bd-587550c158b1

So I created the missing parameters in AWS. And then it ran. But now I am getting.

failed to populate environment: failed to get secret from parameter store: 'SONARQUBE_JDBC_URL': AccessDeniedException: User: arn:aws:sts::651476002431:assumed-role/sonarqube-task-role/b0acc62a-a1f9-45b1-b068-079b6e3046e1 is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-west-1:651476002431:parameter/sonarqube/rds-url

I ran everything like I needed it.  It looks like that key is hardcoded someplace

**Comment by colincoleman** [comment]
Looking into this now - my assumption is that the AWS_REGION parameter is not being passed into / set in the container and therefore defaulting to eu-west-1 (not where your secrets or key are)

**Comment by colincoleman** [comment]
This should be fixed in v1.0.3 - if you have any further issues regarding this please feel free to reopen this ticket.
